spring:
  profiles:
    active: dev

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8888
  servlet:
    context-path: /admin

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: cn.mhonor.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null